### ISSUE TITLE
add:  CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by vidhi-mody** [vidhi-mody/EmpowHer#10]
A code of conduct defines standards for how to engage in a community. [Read more](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)
> Please add the link to the Code of Conduct in the README. [Refer here](https://github.com/twitter/code-of-conduct)

Examples:
- [Twitter](https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md)
- [Docker](https://github.com/docker/code-of-conduct/blob/master/code-of-conduct-EN.md)

**Comment by shivanshi-s** [comment]
Hello, I would like to work on this issue, please assign this to me under LGMSOC21

**Comment by swathi-469** [comment]
Hi I would like to work on this issue
