### ISSUE TITLE
CONTRIBUTION Guidelines

### ISSUE THREAD

**Issue by swathi-469** [vidhi-mody/EmpowHer#11]
I would like add a Contribution guidelines for open source beginners . Please assign this to me

**Comment by vidhi-mody** [comment]
@swathi-469 sure go ahead!

**Comment by vidhi-mody** [comment]
@swathi-469 can you elaborate on what you want to work on? An issue for adding the code of the conduct is already open

**Comment by swathi-469** [comment]
Yeah sure like Standards, Enforcement Responsibilities , Scope ,etc ..

**Comment by swathi-469** [comment]
explain step by step procedure along with images that are a beginner friendly

**Comment by swathi-469** [comment]
Can i start working on it

**Comment by vidhi-mody** [comment]
@swathi-469 can you link some resources/ sample code of the contribution guide you want to work on so I can understand this better?

**Comment by swathi-469** [comment]
Please refer to this link mam 
Similarly I can do it 
https://github.com/swathi-469/Uplift-Web/blob/main/CONTRIBUTING.md

**Comment by vidhi-mody** [comment]
@swathi-469 there are some other high priority issues we've created. Would prefer if those are taken care of first. It would be really helpful if you could work on finding bugs and reporting them or suggest some features to improve the platform.

**Comment by swathi-469** [comment]
I am completely a beginner in open source mam that's why I thought doing from beginner level
