### ISSUE TITLE
move the badges to top and add some more

### ISSUE THREAD

**Issue by Umesh-01** [vidhi-mody/EmpowHer#14]
### Description
Move the badges to the top and add some more badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help the users to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/125403492-33b47080-e3d3-11eb-86c8-a46858788d5a.png)

### Solution
I will move the badges to the top of Readme file, add some more badges and also will add links related to them so that the README.md file will look more interactive and awesome.

- [ ] I will move them to the top
- [ ] I will align them to the center
- [ ] I will add some more badges
- [ ] I will add links to the badges

### **Work under/as**
- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@vidhi-mody @und3fined-v01d should I work on this??

**Comment by sovoid** [comment]
Hi @Umesh-01 there are some other high priority issues we've created. Would prefer if those are taken care of first
